services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: todo-sql
    environment:
      SA_PASSWORD: "thinphat04"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build: .
    container_name: todo-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__MyConnection: "Server=db,1433;Database=todo;User Id=sa;Password=thinphat04;TrustServerCertificate=True;"
    ports:
      - "5001:80"
    restart: on-failure

volumes:
  sql_data:
