services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: todo-sql
    environment:
      SA_PASSWORD: "thinhphat04"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
<<<<<<< HEAD
    build: .  
    container_name: todo-api-container
=======
    build: .  # context là thư mục hiện tại
    container_name: todo-api
>>>>>>> 3e2ef6c0739fea7c0192ea0b3ab21fae6faf18a5
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__MyConnection: "Server=db,1433;Database=todo;User Id=SA;Password=thinhphat04;TrustServerCertificate=True;"
    ports:
      - "5001:80"
    restart: on-failure

volumes:
  sql_data:
